version: '2'
services:
  app:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./infrastructure/config/nginx.conf:/etc/nginx/nginx.conf
      - ./infrastructure/config/fpm-pool.conf:/etc/php7/php-fpm.d/zzz_custom.conf
      - ./infrastructure/config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./:/var/www/html
    restart: always
    ports:
      - 80:80
